import { useRef, useCallback } from 'react'

/**
 * Generates brown noise (red noise) via the Web Audio API.
 * Brown noise has a 1/f² power spectrum — warmer and deeper than white or
 * pink noise, widely used for focus and concentration.
 *
 * Generated by integrating white noise samples, which produces the
 * characteristic low-frequency rolloff.
 */

const VOLUME = 0.35
const FADE_IN_S = 2.5
const FADE_OUT_TAU = 1.2 // time constant for exponential fade-out

function buildBrownNoiseBuffer(ctx: AudioContext): AudioBuffer {
  // 8-second mono buffer — long enough that looping is inaudible
  const length = ctx.sampleRate * 8
  const buffer = ctx.createBuffer(1, length, ctx.sampleRate)
  const data = buffer.getChannelData(0)

  let lastOut = 0
  for (let i = 0; i < length; i++) {
    const white = Math.random() * 2 - 1
    // Leaky integrator — accumulates low frequencies, rolls off highs
    data[i] = (lastOut + 0.02 * white) / 1.02
    lastOut = data[i]
    data[i] *= 3.5 // compensate for energy loss from integration
  }

  return buffer
}

export function useBrownNoise() {
  const ctxRef    = useRef<AudioContext | null>(null)
  const sourceRef = useRef<AudioBufferSourceNode | null>(null)
  const gainRef   = useRef<GainNode | null>(null)
  const activeRef = useRef(false)

  function getCtx(): AudioContext {
    if (!ctxRef.current || ctxRef.current.state === 'closed') {
      ctxRef.current = new AudioContext()
    }
    return ctxRef.current
  }

  const start = useCallback(() => {
    if (activeRef.current) return

    const ctx = getCtx()
    if (ctx.state === 'suspended') ctx.resume()

    const gain = ctx.createGain()
    gain.gain.setValueAtTime(0, ctx.currentTime)
    gain.gain.linearRampToValueAtTime(VOLUME, ctx.currentTime + FADE_IN_S)
    gain.connect(ctx.destination)

    const source = ctx.createBufferSource()
    source.buffer = buildBrownNoiseBuffer(ctx)
    source.loop = true
    source.connect(gain)
    source.start()

    sourceRef.current = source
    gainRef.current   = gain
    activeRef.current = true
  }, [])

  const stop = useCallback(() => {
    if (!activeRef.current || !gainRef.current || !ctxRef.current) return

    const ctx  = ctxRef.current
    const gain = gainRef.current
    gain.gain.setTargetAtTime(0, ctx.currentTime, FADE_OUT_TAU)

    // Stop the source after the fade completes (~4× tau)
    setTimeout(() => {
      try { sourceRef.current?.stop() } catch { /* already stopped */ }
      sourceRef.current = null
      gainRef.current   = null
      activeRef.current = false
    }, FADE_OUT_TAU * 4 * 1000)
  }, [])

  const suspend = useCallback(() => {
    ctxRef.current?.suspend()
  }, [])

  const resumeCtx = useCallback(() => {
    ctxRef.current?.resume()
  }, [])

  return { start, stop, suspend, resumeCtx }
}
